seed: 0
use_vr: false
show_gui: false
data_path: data
save_dir: /tmp
record: true

defaults:
  - cameras: static
  - env: play_table_env
  - scene: calvin_scene_D
  - robot: panda_longer_finger
  - tasks: customized_tasks
