#misc
# device: ${device}
discount: 0.99

#rl dataset
batch_size: 32

#actor
actor_lr: 3e-5

#critic
critic_lr: 3e-5
critic_tau: 0.005

#alpha
alpha_lr: 3e-5
init_alpha: 0.01

# #ae
# ae_lr: 3e-4
# shared_encoder: true
# fixed_encoder: false

# evaluation frequency:
eval_frequency: ${eval_frequency}
