deterministic: true
accelerator: gpu
devices: auto
strategy: auto #"ddp", "ddp_spawn", "deepspeed"
precision: 32
max_epochs: -1
max_steps: 8e4 # 10K episodes
log_every_n_steps:       1             #help='print/disp/save frequency'
resume_from_checkpoint:  null            #help='path to latest checkpoint'
val_check_interval:      1.0             #help=How often to check the validation set.
limit_val_batches:       1.0
accumulate_grad_batches: 1               #help='number of accumulated batches'