defaults:
  - gmm: riepybdlib_gmm # manifold_gmm or bayesian_gmm or riepybdlib_gmm
  - skill: default
  - env: default_skill # open_drawer / close_drawer / ?

  - _self_

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

skill:
  name: move_slider_left
  max_steps: 96